include themes/flexoki-dark.conf
#include themes/flexoki_light.conf

font_size 14
font_family      IosevkaTerm Nerd Font 
# font_family      IosevkaTerm Nerd Font Mono
# font_family     IosevkaTermSlab Nerd Font

bold_font        IosevkaTerm Nerd Font
italic_font      auto
bold_italic_font auto

background_opacity 0.8
term xterm-256color
keyboard_protocol legacy

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.20 0.60
enable_audio_bell no
