[colors.normal]
black = "#000000"
red = "#ff3333"
green = "#b8cc52"
yellow = "#e7c547"
blue = "#36a3d9"
magenta = "#f07178"  # Заменяем purple на magenta
cyan = "#95e6cb"
white = "#ffffff"

[colors.bright]
black = "#323232"
red = "#ff6565"
green = "#eafe84"
yellow = "#fff779"
blue = "#68d5ff"
magenta = "#ffa3aa"  # Заменяем purple на magenta
cyan = "#c7fffd"
white = "#ffffff"

[colors.primary]
background = "#0f1419"
foreground = "#e6e1cf"

[colors.selection]
text = "#ffffff"  # Цвет текста выделения (можно настроить по желанию)
background = "#253340"

[colors.cursor]
cursor = "#f29718"  # Цвет курсора