#preload = /home/yerza/.config/hypr/wallpapers/Dark_Nature.png
#wallpaper = eDP-1, /home/yerza/.config/hypr/wallpapers/Dark_Nature.png

preload = /home/yerza/.config/hypr/wallpapers/Wallpaper1.png
wallpaper = eDP-1, /home/yerza/.config/hypr/wallpapers/Wallpaper1.png
